# Thuật toán FIFO

In [182]:
#Thuật toán FIFO
lst= [1,3,5,6,3,5,7,1,4,7,5,3,1,6,3,2,4,1,3,7]
row1=[]
row2=[]
row3=[]
cache=[]
index=0
mistake=[]
for i in range(len(lst)):
    if i<3:
        row1.append(lst[0])
        if i>=1:
            row2.append(lst[1])
        else:
            row2.append(" ")
        if i==2:
            row3.append(lst[2])
        else:
            row3.append(" ")
        cache.append(lst[i])
        mistake.append("*")
    elif len(cache)==3:
        if lst[i] not in cache:
            cache[index]=lst[i]
            index+=1
            if index==3:
                index =0
            row1.append(cache[0])
            row2.append(cache[1])
            row3.append(cache[2])
            mistake.append("*")
        else:
            row1.append(cache[0])
            row2.append(cache[1])
            row3.append(cache[2])
            mistake.append(" ")
lst=[str(i) for i in lst]
row1=[str(i) for i in row1]
row2=[str(i) for i in row2]
row3=[str(i) for i in row3]
print("Thuật toán FIFO")
print("  ".join(lst))
print("  ".join(row1))
print("  ".join(row2))
print("  ".join(row3))
print("  ".join(mistake))
print("Số lỗi:",mistake.count("*"))

Thuật toán FIFO
1  3  5  6  3  5  7  1  4  7  5  3  1  6  3  2  4  1  3  7
1  1  1  6  6  6  6  6  4  4  4  4  1  1  1  1  4  4  4  7
   3  3  3  3  3  7  7  7  7  5  5  5  6  6  6  6  1  1  1
      5  5  5  5  5  1  1  1  1  3  3  3  3  2  2  2  3  3
*  *  *  *        *  *  *     *  *  *  *     *  *  *  *  *
Số lỗi: 16


In [178]:
set(lst)

{'1', '2', '3', '4', '5', '6', '7'}

# Thuật toán tối ưu

In [183]:
#Thuật toán Tối Ưu
lst= [1,3,5,6,3,5,7,1,4,7,5,3,1,6,3,2,4,1,3,7]
row1=[]
row2=[]
row3=[]
cache=[]
mistake=[]
def longest(ca,ls):
    re=[]
    for i in ca:
        if i in ls:
            r=ls.index(i)
            re.append(r)
        elif i not in ls:
            re.append(-1)
    length=max(re)
    result=ls[length]
    if -1 in re:
        count= re.count(-1)
        if count==1:
            result=ca[re.index(-1)]
        elif count==2:
            couple=[]
            for i in range(len(re)):
                if re[i]==-1:
                    couple.append(i)
            index= couple[0] if ca[couple[0]]<ca[couple[1]] else couple[1]
            result= ca[index]
        else:
            result= min(ca)
    return result
for i in range(len(lst)):
    if i<3:
        row1.append(lst[0])
        if i>=1:
            row2.append(lst[1])
        else:
            row2.append(" ")
        if i==2:
            row3.append(lst[2])
        else:
            row3.append(" ")
        cache.append(lst[i])
        mistake.append("*")
    elif len(cache)==3:
        if lst[i] not in cache:
            longest_factor = longest(cache,lst[i:])
            cache[cache.index(longest_factor)]=lst[i]
            row1.append(cache[0])
            row2.append(cache[1])
            row3.append(cache[2])
            mistake.append("*")
        else:
            row1.append(cache[0])
            row2.append(cache[1])
            row3.append(cache[2])
            mistake.append(" ")
lst=[str(i) for i in lst]
row1=[str(i) for i in row1]
row2=[str(i) for i in row2]
row3=[str(i) for i in row3]
print("Thuật toán Tối ưu:")
print("  ".join(lst))
print("  ".join(row1))
print("  ".join(row2))
print("  ".join(row3))
print("  ".join(mistake))
print("Số lỗi:",mistake.count("*"))

Thuật toán Tối ưu:
1  3  5  6  3  5  7  1  4  7  5  3  1  6  3  2  4  1  3  7
1  1  1  6  6  6  7  7  7  7  7  7  1  6  6  2  2  1  1  7
   3  3  3  3  3  3  1  4  4  4  4  4  4  4  4  4  4  4  4
      5  5  5  5  5  5  5  5  5  3  3  3  3  3  3  3  3  3
*  *  *  *        *  *  *        *  *  *     *     *     *
Số lỗi: 13


# Thuật toán LRU

In [184]:
#Thuật toán LRU
lst= [1,3,5,6,3,5,7,1,4,7,5,3,1,6,3,2,4,1,3,7]
row1=[]
row2=[]
row3=[]
cache=[]
used=[]
mistake=[]
for i in range(len(lst)):
    if i<3:
        row1.append(lst[0])
        if i>=1:
            row2.append(lst[1])
        else:
            row2.append(" ")
        if i==2:
            row3.append(lst[2])
        else:
            row3.append(" ")
        cache.append(lst[i])
        used.append(lst[i])
        mistake.append("*")
    elif len(cache)==3:
        if lst[i] not in cache:
            index = cache.index(used[0])
            cache[index]=lst[i]
            used.remove(used[0])
            used.append(lst[i])
            if index==3:
                index =0
            row1.append(cache[0])
            row2.append(cache[1])
            row3.append(cache[2])
            mistake.append("*")
        else:
            used.remove(lst[i])
            used.append(lst[i])
            row1.append(cache[0])
            row2.append(cache[1])
            row3.append(cache[2])
            mistake.append(" ")
lst=[str(i) for i in lst]
row1=[str(i) for i in row1]
row2=[str(i) for i in row2]
row3=[str(i) for i in row3]
print("Thuật toán LRU:")
print("  ".join(lst))
print("  ".join(row1))
print("  ".join(row2))
print("  ".join(row3))
print("  ".join(mistake))
print("Số lỗi:",mistake.count("*"))

Thuật toán LRU:
1  3  5  6  3  5  7  1  4  7  5  3  1  6  3  2  4  1  3  7
1  1  1  6  6  6  7  7  7  7  7  7  1  1  1  2  2  2  3  3
   3  3  3  3  3  3  1  1  1  5  5  5  6  6  6  4  4  4  7
      5  5  5  5  5  5  4  4  4  3  3  3  3  3  3  1  1  1
*  *  *  *        *  *  *     *  *  *  *     *  *  *  *  *
Số lỗi: 16


# Thuật toán Banking

In [181]:
import numpy as np
allocation_mt=np.array([[1,0,0,0],[0,0,1,2],[1,3,5,4],[0,6,3,2],[0,0,1,4]])
max_mt=np.array([[1,7,5,0],[0,0,1,2],[2,3,5,6],[0,6,5,2],[0,6,5,6]])
available= np.array([1,5,2,0])
need_mt= max_mt - allocation_mt
work = np.array([i for i in available])
work_step=np.array([i for i in work])
step=[]
while len(step) != 5:
    for i in range(len(need_mt)):
        if i not in step:
            check =work - need_mt[i]
            if True not in (check < 0):
                work += allocation_mt[i]
                step.append(i)
                work_step=np.vstack((work_step,work))
print("a.Ma trận Needij= Maxij–Allocationij ")
print("Ma trận Need:\n",need_mt)
steps=[i+1 for i in step]
count=0
print(f"b.Tìm chuỗi an toàn, đầu tiên thử với i=1,2,..., ta được P{steps[0]}")
print(f"i={steps[0]}   Need{steps[0]} ={need_mt[step[0]]}<=Work={work_step[0]}?  Thoả mãn \n=> Chuỗi an toàn nếu có thì P{steps[0]} đứng đầu và dùng bảng sau để lưu kết quả các bước ")
print("Work>=\t\tNeed[i]\t\tP[i]\tAllocation[i]")
for i in step:
    print(work_step[count],need_mt[i],f"P{str(steps[count])}",allocation_mt[i],sep="\t")
    count+=1
print("Kết luận: Hệ thống an toàn vì tìm được ít nhất một chuỗi an toàn <,,,,,>")

a.Ma trận Needij= Maxij–Allocationij 
Ma trận Need:
 [[0 7 5 0]
 [0 0 0 0]
 [1 0 0 2]
 [0 0 2 0]
 [0 6 4 2]]
b.Tìm chuỗi an toàn, đầu tiên thử với i=1,2,..., ta được P2
i=2   Need2 =[0 0 0 0]<=Work=[1 5 2 0]?  Thoả mãn 
=> Chuỗi an toàn nếu có thì P2 đứng đầu và dùng bảng sau để lưu kết quả các bước 
Work>=		Need[i]		P[i]	Allocation[i]
[1 5 2 0]	[0 0 0 0]	P2	[0 0 1 2]
[1 5 3 2]	[1 0 0 2]	P3	[1 3 5 4]
[2 8 8 6]	[0 0 2 0]	P4	[0 6 3 2]
[ 2 14 11  8]	[0 6 4 2]	P5	[0 0 1 4]
[ 2 14 12 12]	[0 7 5 0]	P1	[1 0 0 0]
Kết luận: Hệ thống an toàn vì tìm được ít nhất một chuỗi an toàn <,,,,,>


In [185]:
import numpy as np
allocation_mt=np.array([[0,0,1,4],[1,0,0,0],[1,3,5,4],[0,6,3,2],[0,0,1,2]])
max_mt=np.array([[0,6,5,6],[1,7,5,0],[2,3,5,6],[0,6,5,2],[0,0,1,2]])
available= np.array([1,5,2,0])
need_mt= max_mt - allocation_mt
work = np.array([i for i in available])
work_step=np.array([i for i in work])
step=[]
while len(step) != 5:
    for i in range(len(need_mt)):
        if i not in step:
            check =work - need_mt[i]
            if True not in (check < 0):
                work += allocation_mt[i]
                step.append(i)
                work_step=np.vstack((work_step,work))
print("a.Ma trận Needij= Maxij–Allocationij ")
print("Ma trận Need:\n",need_mt)
steps=[i+1 for i in step]
count=0
print(f"b.Tìm chuỗi an toàn, đầu tiên thử với i=1,2,..., ta được P{steps[0]}")
print(f"i={steps[0]}   Need{steps[0]} ={need_mt[step[0]]}<=Work={work_step[0]}?  Thoả mãn \n=> Chuỗi an toàn nếu có thì P{steps[0]} đứng đầu và dùng bảng sau để lưu kết quả các bước ")
print("Work>=\t\tNeed[i]\t\tP[i]\tAllocation[i]")
for i in step:
    print(work_step[count],need_mt[i],f"P{str(steps[count])}",allocation_mt[i],sep="\t")
    count+=1

a.Ma trận Needij= Maxij–Allocationij 
Ma trận Need:
 [[0 6 4 2]
 [0 7 5 0]
 [1 0 0 2]
 [0 0 2 0]
 [0 0 0 0]]
b.Tìm chuỗi an toàn, đầu tiên thử với i=1,2,..., ta được P4
i=4   Need4 =[0 0 2 0]<=Work=[1 5 2 0]?  Thoả mãn 
=> Chuỗi an toàn nếu có thì P4 đứng đầu và dùng bảng sau để lưu kết quả các bước 
Work>=		Need[i]		P[i]	Allocation[i]
[1 5 2 0]	[0 0 2 0]	P4	[0 6 3 2]
[ 1 11  5  2]	[0 0 0 0]	P5	[0 0 1 2]
[ 1 11  6  4]	[0 6 4 2]	P1	[0 0 1 4]
[ 1 11  7  8]	[0 7 5 0]	P2	[1 0 0 0]
[ 2 11  7  8]	[1 0 0 2]	P3	[1 3 5 4]
